runtime: python39
service: default
entrypoint: gunicorn -b :$PORT app:app
instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

env_variables:
  MONGODB_URI: ${MONGODB_URI}
  STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
  FRONTEND_URL: "https://tastory.app"

handlers:
  - url: /.*
    script: auto
    secure: always
