#!/bin/bash

# Continue deployment after manual project creation
# Usage: ./scripts/manual-deploy-after-project.sh

set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Configuration
PROJECT_ID="tastory-hackathon"
REGION="us-central1"
SERVICE_NAME="tastory-api"

echo -e "${GREEN}🚀 Continuing Tastory deployment...${NC}"

# Set the project
echo -e "\n${YELLOW}Setting project...${NC}"
gcloud config set project $PROJECT_ID

# Continue from Step 3 of the original script
echo -e "\n${YELLOW}Step 3: Enabling required APIs...${NC}"
gcloud services enable cloudbuild.googleapis.com
gcloud services enable run.googleapis.com
gcloud services enable containerregistry.googleapis.com
gcloud services enable secretmanager.googleapis.com
gcloud services enable firebase.googleapis.com

# Step 4: Set up MongoDB URI in Secret Manager
echo -e "\n${YELLOW}Step 4: Setting up secrets...${NC}"
if [ -z "$MONGODB_URI" ]; then
    if [ -f .env ]; then
        source .env
    fi
fi

if [ -z "$MONGODB_URI" ]; then
    echo -e "${RED}❌ MONGODB_URI not found${NC}"
    echo "Please set MONGODB_URI environment variable or add it to .env file"
    exit 1
fi

# Create or update secret
echo "mongodb_uri=$MONGODB_URI" | gcloud secrets create mongodb-uri --data-file=- 2>/dev/null || \
echo "mongodb_uri=$MONGODB_URI" | gcloud secrets versions add mongodb-uri --data-file=-

# Get the project number for the default service account
PROJECT_NUMBER=$(gcloud projects describe $PROJECT_ID --format="value(projectNumber)")

# Grant Cloud Run access to the secret using the default compute service account
gcloud secrets add-iam-policy-binding mongodb-uri \
    --member="serviceAccount:${PROJECT_NUMBER}-compute@developer.gserviceaccount.com" \
    --role="roles/secretmanager.secretAccessor"

# Step 5: Build and deploy backend to Cloud Run
echo -e "\n${YELLOW}Step 5: Deploying backend to Cloud Run...${NC}"

# Build and deploy in one step
gcloud run deploy $SERVICE_NAME \
    --source . \
    --platform managed \
    --region $REGION \
    --allow-unauthenticated \
    --port 8080 \
    --min-instances 1 \
    --max-instances 100 \
    --memory 512Mi \
    --cpu 1 \
    --timeout 300 \
    --set-env-vars "DB_NAME=tastory,RECIPES_COLLECTION=recipes" \
    --set-secrets "MONGODB_URI=mongodb-uri:latest"

# Get the service URL
SERVICE_URL=$(gcloud run services describe $SERVICE_NAME --region $REGION --format 'value(status.url)')
echo -e "${GREEN}✅ Backend deployed to: $SERVICE_URL${NC}"

# Step 6: Update frontend configuration
echo -e "\n${YELLOW}Step 6: Updating frontend configuration...${NC}"
cat > frontend/.env.production.local << EOF
# Auto-generated by manual-deploy-after-project.sh
REACT_APP_API_URL=$SERVICE_URL
REACT_APP_ENABLE_TTS=true
REACT_APP_ENABLE_RECENT_SEARCHES=true
REACT_APP_ENABLE_STATS_DISPLAY=true
EOF

echo -e "${GREEN}✅ Frontend configuration updated${NC}"

# Step 7: Build frontend
echo -e "\n${YELLOW}Step 7: Building frontend...${NC}"
cd frontend
npm install
npm run build
cd ..

# Step 8: Deploy frontend to Firebase
echo -e "\n${YELLOW}Step 8: Deploying frontend to Firebase...${NC}"

# Check if Firebase CLI is installed
if ! command -v firebase &> /dev/null; then
    echo -e "${YELLOW}Installing Firebase CLI...${NC}"
    npm install -g firebase-tools
fi

# Deploy to Firebase Hosting
firebase deploy --only hosting --project $PROJECT_ID

# Get the hosting URL
HOSTING_URL="https://$PROJECT_ID.web.app"

# Step 10: Summary
echo -e "\n${GREEN}🎉 Deployment Complete!${NC}"
echo -e "\n${YELLOW}Your application is now live:${NC}"
echo -e "Frontend: ${GREEN}$HOSTING_URL${NC}"
echo -e "Backend API: ${GREEN}$SERVICE_URL${NC}"
echo -e "\n${YELLOW}Useful commands:${NC}"
echo "View logs: gcloud run logs read --service $SERVICE_NAME"
echo "Stream logs: gcloud run logs tail --service $SERVICE_NAME"
echo "Update backend: gcloud run deploy $SERVICE_NAME --source ."
echo "Update frontend: cd frontend && npm run build && firebase deploy"
echo -e "\n${YELLOW}Monitoring:${NC}"
echo "Cloud Run: https://console.cloud.google.com/run?project=$PROJECT_ID"
echo "Firebase: https://console.firebase.google.com/project/$PROJECT_ID"

# Optional: Open the app in browser
echo -e "\n${YELLOW}Would you like to open the app in your browser? (y/n)${NC}"
read -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    open "$HOSTING_URL"
fi 