name: Dependency Review

on:
  pull_request:
    branches: [development, stable, main]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    continue-on-error: true # Don't block PR merge for dependency issues initially
    steps:
      - uses: actions/checkout@v4

      - name: Python Dependency Review
        uses: actions/dependency-review-action@v4
        continue-on-error: true
        with:
          fail-on-severity: high
          allow-licenses: MIT, Apache-2.0, BSD-3-Clause, BSD-2-Clause, ISC, Python-2.0

      - name: Check Python dependencies with pip-audit
        continue-on-error: true
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit
          pip install -r requirements.txt
          pip-audit --desc

      - name: Check npm dependencies
        continue-on-error: true
        working-directory: ./frontend
        run: |
          npm audit --production || true

  outdated-check:
    name: Check Outdated Dependencies
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Check outdated Python packages
        run: |
          python -m pip install --upgrade pip
          pip list --outdated || true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Check outdated npm packages
        working-directory: ./frontend
        run: |
          npm outdated || true
